site_name: Laravel Tutorial Manual
site_description: 'Laravel manual project for class'
site_author: 'akusaiful'
site_url: ''

# Repository
# repo_name: 'my-github-handle/my-project'
# repo_url: 'https://github.com/john-doe/my-project'

# Copyright
copyright: 'Copyright &copy; 2022 akusaiful'

theme:
  name: material  
  # name: mkdocs
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/git-alt  
  font:
    text: Roboto
    code: 'Roboto Mono'
  palette:
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo

    # - scheme: default
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
    #   primary: pink
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
    #   primary: indigo
plugins:
    - search
    # - git-revision-date

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:   
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true  
      linenums: true   
      # auto_title: true   
      linenums_style: pymdownx-inline
      
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true    
  - admonition
  # - codehilite  
  - attr_list  
  
  - pymdownx.snippets
  - pymdownx.superfences
   
  # - pymdownx.emoji:
  #     emoji_index:  !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
- Intro: 
  - Introduction: index.md
  - Class Guide: guide.md  
  - Installation: installation.md
  - Laravel Architecture: structure.md
  - Hello Laravel (Route) : hello-laravel.md
  - Blade Template : templating.md
  - Tugasan 0 : tugasan_0_structure_to_object.md
  - Tugasan 1 : tugasan_1.md
  - Tugasan 2 : tugasan_2.md
  - Tugasan 3 : tugasan_3.md

- Route:
  - Routing: route_routing.md  
  - Link: route_link.md

- Database:   
  - Configuration: db.md
  - Migration : database_migration.md
  - Seeder: seeder.md
  - Faker Library: faker.md
  - Model: model.md
  - Factory: factory.md
  - Controller: controller.md

- CRUD:
  - CRUD Explain: crud_explain.md  
  - CRUD Example: crud_full.md
  - Pagination: pagination.md
  - Request Validation: form_validation.md
  - Searching: search.md    
  - Model Scopes: local_scopes.md
  - Search Query: search_query.md
  
  
  # - Blade: blade.md  
- Eloquent: 
  - Eloquent: eloquent.md  
  - Relationship : relationship.md
  - SQL Debugging: debugging.md
  - Date Casting : date_casting.md

- Auth:
  - Installation: auth_install.md
  - Visibility: auth_visibility.md
  - Protecting Route: authentication.md
  - Eloquent Auth: auth_eloquent.md
  - Email Verification: auth_email_verification.md
  - Password Confirm Page : auth_password_confirm_page.md

- Mail: 
  - Setup: mail_setup.md  
  - Mail Assignment: mail_assignment.md

- Upload: 
  - Upload File: upload.md  

- PDF: 
  - Generate PDF: pdf.md

- Translation:
  - Setup: translation.md
  - Transalation Middleware: translation_middleware.md
  
- Utils:   
  - Helpers: helper.md
  - Breadcrumb: breadcrumb.md
  - Remove Public: remove_public.md
  - Auto Refresh Browser: refresh_browser.md
  
- Package:
  - Setup Package: package_install.md
  - Debugbar: package_debugbar.md
  - Web Tinker: package_webtinker.md
  - Extender Controller: package_extender_controller.md
  - Sweetalert: package_sweetalert.md
  - Grid: package_grid.md
  - Action: package_action.md
  - Join: package_power_join.md

- Reference:
  - Template: template.md
  - Code Complete : code_complete.md
  - eBook: ebook.md
  - Reading: reading.md
  - VSC Extension: vsc_extension.md
  - Package : package.md
  - Voyager: voyager.md 
  - Composer: composer.md
  - Artisan Command: artisan.md
  # - Markdown Tips : markdown.md
  - Manual Reference: manual_reference.md
  # - Introduction: index.md
  # - Class Guide: guide.md
  # - Installation: installation.md
  # - Laravel Structure: structure.md
  # - Hello Laravel : hello-laravel.md
  # - Blade Template : templating.md
  # - Database Conf: db.md
  # - Migration : database_migration.md
  # # - Seeder: seeder.md
  # - Model: model.md
  # - Controller: controller.md
  # - Routing: routing.md  
  
  # - Working with CRUD:
  #   - CRUD Scaffolding: form_crud.md
  #   - Pagination: pagination.md
  #   - Request Validation: form_validation.md
  #   - Scopes: local_scopes.md
  #   - Search Query: search_query.md
  
  # # - Blade: blade.md
  # - User Login: user_login.md
  # - Auth Scaffold: authentication.md
  
  # - Eloquent: 
  #   - Eloquent: eloquent.md  
  #   - Relationship : relationship.md

  # - Upload File: upload.md  
  # - SQL Debugging: debugging.md
  
  # - Helpers: helper.md
  # - Laravel Package:
  #   - Package : package.md
  #   - Voyager: voyager.md
  # - Command:
  #   - Composer: composer.md
  #   - Artisan Command: artisan.md
  #   - Markdown Tips : markdown.md
  # - Reference: resource.md
  
